version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nbd
      - MONGO_INITDB_ROOT_PASSWORD=nbdpassword
    volumes:
      - pg:/var/lib/mongodb/data
    ports:
      - "27017:27017"
    restart: unless-stopped
volumes:
  pg:



